// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `record_activate_total_nanos`, `record_bm25_rebuild_nanos`, `record_hnsw_load_nanos`, `record_hnsw_rebuild_nanos`, `record_hnsw_save_nanos`, `record`, `reset`, `snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AtomicTimingCounter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

ActivationTimingStats activationTimingStats() =>
    RustLib.instance.api.crateApiActivationMetricsActivationTimingStats();

void resetActivationTimingStats() =>
    RustLib.instance.api.crateApiActivationMetricsResetActivationTimingStats();

ActivationTimingStats takeActivationTimingStats() =>
    RustLib.instance.api.crateApiActivationMetricsTakeActivationTimingStats();

class ActivationTimingStats {
  final BigInt activateTotalNanos;
  final BigInt activateCount;
  final BigInt bm25RebuildNanos;
  final BigInt bm25RebuildCount;
  final BigInt hnswLoadNanos;
  final BigInt hnswLoadCount;
  final BigInt hnswLoadSuccessCount;
  final BigInt hnswLoadMissCount;
  final BigInt hnswRebuildNanos;
  final BigInt hnswRebuildCount;
  final BigInt hnswSaveNanos;
  final BigInt hnswSaveCount;

  const ActivationTimingStats({
    required this.activateTotalNanos,
    required this.activateCount,
    required this.bm25RebuildNanos,
    required this.bm25RebuildCount,
    required this.hnswLoadNanos,
    required this.hnswLoadCount,
    required this.hnswLoadSuccessCount,
    required this.hnswLoadMissCount,
    required this.hnswRebuildNanos,
    required this.hnswRebuildCount,
    required this.hnswSaveNanos,
    required this.hnswSaveCount,
  });

  @override
  int get hashCode =>
      activateTotalNanos.hashCode ^
      activateCount.hashCode ^
      bm25RebuildNanos.hashCode ^
      bm25RebuildCount.hashCode ^
      hnswLoadNanos.hashCode ^
      hnswLoadCount.hashCode ^
      hnswLoadSuccessCount.hashCode ^
      hnswLoadMissCount.hashCode ^
      hnswRebuildNanos.hashCode ^
      hnswRebuildCount.hashCode ^
      hnswSaveNanos.hashCode ^
      hnswSaveCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivationTimingStats &&
          runtimeType == other.runtimeType &&
          activateTotalNanos == other.activateTotalNanos &&
          activateCount == other.activateCount &&
          bm25RebuildNanos == other.bm25RebuildNanos &&
          bm25RebuildCount == other.bm25RebuildCount &&
          hnswLoadNanos == other.hnswLoadNanos &&
          hnswLoadCount == other.hnswLoadCount &&
          hnswLoadSuccessCount == other.hnswLoadSuccessCount &&
          hnswLoadMissCount == other.hnswLoadMissCount &&
          hnswRebuildNanos == other.hnswRebuildNanos &&
          hnswRebuildCount == other.hnswRebuildCount &&
          hnswSaveNanos == other.hnswSaveNanos &&
          hnswSaveCount == other.hnswSaveCount;
}
