// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_cjk`, `is_noncharacter_code_point`, `is_private_use_code_point`, `join_pages`, `normalize_extracted_text`, `remove_trailing_page_number`

/// Extract text content from a PDF file (bytes)
/// Uses page-by-page extraction for safe page number removal and hyphenation handling
Future<String> extractTextFromPdf({required List<int> fileBytes}) =>
    RustLib.instance.api
        .crateApiDocumentParserExtractTextFromPdf(fileBytes: fileBytes);

/// Extract text content from a DOCX file (bytes)
Future<String> extractTextFromDocx({required List<int> fileBytes}) =>
    RustLib.instance.api
        .crateApiDocumentParserExtractTextFromDocx(fileBytes: fileBytes);

/// Auto-detect document type and extract text
/// Uses magic bytes to determine file format
Future<String> extractTextFromDocument({required List<int> fileBytes}) =>
    RustLib.instance.api
        .crateApiDocumentParserExtractTextFromDocument(fileBytes: fileBytes);

/// Decode UTF-8 text bytes without altering content semantics.
Future<String> extractTextFromUtf8({required List<int> fileBytes}) =>
    RustLib.instance.api
        .crateApiDocumentParserExtractTextFromUtf8(fileBytes: fileBytes);

/// Read a file and extract text according to extension / magic bytes.
///
/// Text-like files (`.txt`, `.md`, `.markdown`) are decoded as UTF-8.
/// Binary document types fall back to the existing document extractor.
Future<String> extractTextFromFile({required String filePath}) =>
    RustLib.instance.api
        .crateApiDocumentParserExtractTextFromFile(filePath: filePath);
