// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `enter`, `legacy_counters_enabled`, `new`, `record`, `reset`, `snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AtomicCounter`, `LegacyCountingGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `fmt`

IngestTrafficStats ingestTrafficStats() =>
    RustLib.instance.api.crateApiIngestMetricsIngestTrafficStats();

void resetIngestTrafficStats() =>
    RustLib.instance.api.crateApiIngestMetricsResetIngestTrafficStats();

/// Snapshot of all ingest FFI byte/call counters.
///
/// Each field is the cumulative count since the last `reset_ingest_traffic_stats`
/// (or process start). Designed to be diffed around a single ingest call.
class IngestTrafficStats {
  final BigInt legacyAddSourceInBytes;
  final BigInt legacyAddSourceInCalls;
  final BigInt legacyChunkerTextInBytes;
  final BigInt legacyChunkerTextInCalls;
  final BigInt legacyChunkerChunksOutBytes;
  final BigInt legacyChunkerChunksOutCalls;
  final BigInt legacyAddChunksInBytes;
  final BigInt legacyAddChunksInCalls;
  final BigInt sessionPrepareContentInBytes;
  final BigInt sessionPrepareContentInCalls;
  final BigInt sessionEmbeddingTextOutBytes;
  final BigInt sessionEmbeddingTextOutCalls;
  final BigInt sessionCommitEmbeddingsInBytes;
  final BigInt sessionCommitEmbeddingsInCalls;

  const IngestTrafficStats({
    required this.legacyAddSourceInBytes,
    required this.legacyAddSourceInCalls,
    required this.legacyChunkerTextInBytes,
    required this.legacyChunkerTextInCalls,
    required this.legacyChunkerChunksOutBytes,
    required this.legacyChunkerChunksOutCalls,
    required this.legacyAddChunksInBytes,
    required this.legacyAddChunksInCalls,
    required this.sessionPrepareContentInBytes,
    required this.sessionPrepareContentInCalls,
    required this.sessionEmbeddingTextOutBytes,
    required this.sessionEmbeddingTextOutCalls,
    required this.sessionCommitEmbeddingsInBytes,
    required this.sessionCommitEmbeddingsInCalls,
  });

  /// Sum of text-body bytes that crossed FFI on the legacy chain.
  Future<BigInt> legacyTextTrafficTotal() => RustLib.instance.api
      .crateApiIngestMetricsIngestTrafficStatsLegacyTextTrafficTotal(
        that: this,
      );

  /// Sum of text-body bytes that crossed FFI on the IngestSession chain.
  /// Excludes embedding vector bytes (vectors are not text and are tracked
  /// separately for transparency).
  Future<BigInt> sessionTextTrafficTotal() => RustLib.instance.api
      .crateApiIngestMetricsIngestTrafficStatsSessionTextTrafficTotal(
        that: this,
      );

  @override
  int get hashCode =>
      legacyAddSourceInBytes.hashCode ^
      legacyAddSourceInCalls.hashCode ^
      legacyChunkerTextInBytes.hashCode ^
      legacyChunkerTextInCalls.hashCode ^
      legacyChunkerChunksOutBytes.hashCode ^
      legacyChunkerChunksOutCalls.hashCode ^
      legacyAddChunksInBytes.hashCode ^
      legacyAddChunksInCalls.hashCode ^
      sessionPrepareContentInBytes.hashCode ^
      sessionPrepareContentInCalls.hashCode ^
      sessionEmbeddingTextOutBytes.hashCode ^
      sessionEmbeddingTextOutCalls.hashCode ^
      sessionCommitEmbeddingsInBytes.hashCode ^
      sessionCommitEmbeddingsInCalls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngestTrafficStats &&
          runtimeType == other.runtimeType &&
          legacyAddSourceInBytes == other.legacyAddSourceInBytes &&
          legacyAddSourceInCalls == other.legacyAddSourceInCalls &&
          legacyChunkerTextInBytes == other.legacyChunkerTextInBytes &&
          legacyChunkerTextInCalls == other.legacyChunkerTextInCalls &&
          legacyChunkerChunksOutBytes == other.legacyChunkerChunksOutBytes &&
          legacyChunkerChunksOutCalls == other.legacyChunkerChunksOutCalls &&
          legacyAddChunksInBytes == other.legacyAddChunksInBytes &&
          legacyAddChunksInCalls == other.legacyAddChunksInCalls &&
          sessionPrepareContentInBytes == other.sessionPrepareContentInBytes &&
          sessionPrepareContentInCalls == other.sessionPrepareContentInCalls &&
          sessionEmbeddingTextOutBytes == other.sessionEmbeddingTextOutBytes &&
          sessionEmbeddingTextOutCalls == other.sessionEmbeddingTextOutCalls &&
          sessionCommitEmbeddingsInBytes ==
              other.sessionCommitEmbeddingsInBytes &&
          sessionCommitEmbeddingsInCalls ==
              other.sessionCommitEmbeddingsInCalls;
}
