// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decide_duplicate_decision`, `decode_structured_chunk_type`, `encode_structured_chunk_type`, `ensure_active`, `prepare_source_ingestion_inner`, `render_context_text`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DuplicateDecision`, `SessionState`, `StagedChunk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Combined entrypoint: insert/find source row, claim it, run the chunker, and
/// return an `IngestSession` carrying the chunked content. Dart drives the
/// per-batch embedding loop on the returned session.
Future<PreparedIngestion> prepareSourceIngestion({
  required String collectionId,
  required String content,
  String? metadata,
  String? name,
  required IngestStrategy strategy,
  required int maxChars,
  required int overlapChars,
}) => RustLib.instance.api.crateApiIngestSessionPrepareSourceIngestion(
  collectionId: collectionId,
  content: content,
  metadata: metadata,
  name: name,
  strategy: strategy,
  maxChars: maxChars,
  overlapChars: overlapChars,
);

/// UTF-8 bytes variant: skips the Dart `String` materialization step. The
/// caller hands raw bytes (typically a `Uint8List` from a file/network read);
/// the Rust side performs UTF-8 decoding once. Identical staging behavior to
/// `prepare_source_ingestion` once the bytes are decoded.
Future<PreparedIngestion> prepareSourceIngestionFromUtf8({
  required String collectionId,
  required List<int> contentBytes,
  String? metadata,
  String? name,
  required IngestStrategy strategy,
  required int maxChars,
  required int overlapChars,
}) => RustLib.instance.api.crateApiIngestSessionPrepareSourceIngestionFromUtf8(
  collectionId: collectionId,
  contentBytes: contentBytes,
  metadata: metadata,
  name: name,
  strategy: strategy,
  maxChars: maxChars,
  overlapChars: overlapChars,
);

/// File-path variant: Rust reads the file and never round-trips its body
/// through Dart. Only the path string crosses FFI (Dart→Rust). When
/// `strategy_hint` is `None`, the chunking strategy is inferred from the
/// extension (`.md` / `.markdown` → Markdown, otherwise Recursive). Text-like
/// extensions (`.txt`, `.md`, `.markdown`) are decoded as UTF-8; everything
/// else falls through to `document_parser::extract_text_from_document` (PDF /
/// DOCX magic-byte routing).
Future<PreparedIngestion> prepareSourceIngestionFromFile({
  required String collectionId,
  required String filePath,
  String? metadata,
  String? name,
  IngestStrategy? strategyHint,
  required int maxChars,
  required int overlapChars,
}) => RustLib.instance.api.crateApiIngestSessionPrepareSourceIngestionFromFile(
  collectionId: collectionId,
  filePath: filePath,
  metadata: metadata,
  name: name,
  strategyHint: strategyHint,
  maxChars: maxChars,
  overlapChars: overlapChars,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IngestSession>>
abstract class IngestSession implements RustOpaqueInterface {
  /// Roll back: clear any DB chunks that were already committed, mark the
  /// source `failed`, and drop staged content. Idempotent after the first
  /// call; no-op once the session is finalized.
  Future<void> abort();

  /// Flush the current in-flight batch to the chunks table using the
  /// provided embeddings. Returns the number of chunks written.
  ///
  /// Validation is performed *before* draining in_flight so a malformed
  /// embedding payload does not lose chunk content.
  Future<int> commitEmbeddings({required List<ChunkEmbedding> embeddings});

  Future<int> committedCount();

  /// Explicit drop to release the Rust handle from Dart.
  @override
  Future<void> dispose();

  /// Mark the source `completed`. Errors if any chunks are still pending or in flight.
  Future<void> finalize();

  Future<int> inFlightCount();

  Future<int> pendingDispatchCount();

  Future<PlatformInt64> sourceId();

  /// Drain up to `batch_size` chunks from the pending queue. Each chunk's
  /// `embedding_text` is computed from its stored content+chunk_type and
  /// shipped to Dart for ONNX embedding. The corresponding `StagedChunk`
  /// moves to the in-flight slot, awaiting a matching `commit_embeddings`.
  ///
  /// Errors if a previous batch is still in flight (single-batch discipline).
  Future<List<EmbeddingRequest>> takeEmbeddingBatch({required int batchSize});

  Future<int> total();
}

/// Returned per-chunk by Dart and consumed by `IngestSession::commit_embeddings`.
class ChunkEmbedding {
  final int chunkIndex;
  final Float32List embedding;

  const ChunkEmbedding({required this.chunkIndex, required this.embedding});

  @override
  int get hashCode => chunkIndex.hashCode ^ embedding.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChunkEmbedding &&
          runtimeType == other.runtimeType &&
          chunkIndex == other.chunkIndex &&
          embedding == other.embedding;
}

/// Returned per-chunk by `IngestSession::take_embedding_batch`.
class EmbeddingRequest {
  final int chunkIndex;
  final String embeddingText;

  const EmbeddingRequest({
    required this.chunkIndex,
    required this.embeddingText,
  });

  @override
  int get hashCode => chunkIndex.hashCode ^ embeddingText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbeddingRequest &&
          runtimeType == other.runtimeType &&
          chunkIndex == other.chunkIndex &&
          embeddingText == other.embeddingText;
}

/// Chunking strategy selector for `prepare_source_ingestion`.
enum IngestStrategy { recursive, markdown }

/// Result of `prepare_source_ingestion`.
///
/// `session` is `Some` exactly when `state` is `CreatedReady` or `ResumeReady`,
/// signalling Dart to drain embeddings and call `finalize` / `abort` on it.
class PreparedIngestion {
  final PlatformInt64 sourceId;
  final PreparedSourceState state;
  final int totalChunks;
  final String message;
  final IngestSession? session;

  const PreparedIngestion({
    required this.sourceId,
    required this.state,
    required this.totalChunks,
    required this.message,
    this.session,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      state.hashCode ^
      totalChunks.hashCode ^
      message.hashCode ^
      session.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparedIngestion &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          state == other.state &&
          totalChunks == other.totalChunks &&
          message == other.message &&
          session == other.session;
}

/// Outcome of the source-row stage inside `prepare_source_ingestion`.
enum PreparedSourceState {
  /// New source row created and claimed; chunks staged, ready to drain.
  createdReady,

  /// Existing failed/empty-completed source: stale chunks cleared, re-claimed, restaged.
  resumeReady,

  /// Existing completed source with chunks already on disk; nothing to do.
  duplicateSkip,

  /// Existing source in `pending` or `processing` — owned by another worker.
  duplicateInProgress,
}
