// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assert_no_unknown_future_axes`, `bootstrap_axes`, `create_migration_meta_table`, `detect_existing_install`, `initialize_migration_meta`, `read_axes_with`, `read_axis_int`, `read_axis_string`, `upsert_axis`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Read the current 4-axis state from `migration_meta`.
///
/// Intended for diagnostics, telemetry, and gating by future phases (P0-2
/// fingerprint, P1-3 SQL migrations, P1-4 HNSW envelope, P2-5 BM25 stats).
Future<MigrationAxes> readMigrationAxes() =>
    RustLib.instance.api.crateApiMigrationMetaReadMigrationAxes();

/// Read-only snapshot of the four versioning axes plus the last engine version.
class MigrationAxes {
  final PlatformInt64 sqlSchemaVersion;
  final PlatformInt64 hnswFormatVersion;
  final PlatformInt64 bm25StatsVersion;

  /// Empty string means "not yet registered" (P0-2 will populate).
  final String embeddingFingerprint;
  final String lastEngineVersion;

  const MigrationAxes({
    required this.sqlSchemaVersion,
    required this.hnswFormatVersion,
    required this.bm25StatsVersion,
    required this.embeddingFingerprint,
    required this.lastEngineVersion,
  });

  @override
  int get hashCode =>
      sqlSchemaVersion.hashCode ^
      hnswFormatVersion.hashCode ^
      bm25StatsVersion.hashCode ^
      embeddingFingerprint.hashCode ^
      lastEngineVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationAxes &&
          runtimeType == other.runtimeType &&
          sqlSchemaVersion == other.sqlSchemaVersion &&
          hnswFormatVersion == other.hnswFormatVersion &&
          bm25StatsVersion == other.bm25StatsVersion &&
          embeddingFingerprint == other.embeddingFingerprint &&
          lastEngineVersion == other.lastEngineVersion;
}
