// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `resize`
// These functions are ignored because they have generic arguments: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MmapVectorStore>>
abstract class MmapVectorStore implements RustOpaqueInterface {
  /// Appends a vector and returns its byte offset in the mmap file.
  Future<BigInt> append({required List<int> vector});

  Future<void> flush();

  /// Retrieves a vector given its byte offset.
  Future<U8?> get_({required BigInt offset});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<[u8]>>
abstract class U8 implements RustOpaqueInterface {}
