// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `enter`, `record_hybrid_result_content_read`, `record_hydrated_content_read`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `QueryContentReadGuard`, `QueryContentReadPhase`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`

QueryContentReadStats queryContentReadStats() =>
    RustLib.instance.api.crateApiQueryMetricsQueryContentReadStats();

void resetQueryContentReadStats() =>
    RustLib.instance.api.crateApiQueryMetricsResetQueryContentReadStats();

QueryContentReadStats takeQueryContentReadStats() =>
    RustLib.instance.api.crateApiQueryMetricsTakeQueryContentReadStats();

class QueryContentReadStats {
  final BigInt hybridResultRows;
  final BigInt hybridResultContentBytes;
  final BigInt fullHydrateRows;
  final BigInt fullHydrateContentBytes;
  final BigInt previewRows;
  final BigInt previewContentBytes;
  final BigInt assemblyRows;
  final BigInt assemblyContentBytes;
  final BigInt unclassifiedRows;
  final BigInt unclassifiedContentBytes;

  const QueryContentReadStats({
    required this.hybridResultRows,
    required this.hybridResultContentBytes,
    required this.fullHydrateRows,
    required this.fullHydrateContentBytes,
    required this.previewRows,
    required this.previewContentBytes,
    required this.assemblyRows,
    required this.assemblyContentBytes,
    required this.unclassifiedRows,
    required this.unclassifiedContentBytes,
  });

  Future<BigInt> contentBytesTotal() => RustLib.instance.api
      .crateApiQueryMetricsQueryContentReadStatsContentBytesTotal(that: this);

  Future<BigInt> hydrationContentBytesTotal() => RustLib.instance.api
      .crateApiQueryMetricsQueryContentReadStatsHydrationContentBytesTotal(
        that: this,
      );

  Future<BigInt> hydrationRowsTotal() => RustLib.instance.api
      .crateApiQueryMetricsQueryContentReadStatsHydrationRowsTotal(that: this);

  Future<BigInt> rowsTotal() => RustLib.instance.api
      .crateApiQueryMetricsQueryContentReadStatsRowsTotal(that: this);

  @override
  int get hashCode =>
      hybridResultRows.hashCode ^
      hybridResultContentBytes.hashCode ^
      fullHydrateRows.hashCode ^
      fullHydrateContentBytes.hashCode ^
      previewRows.hashCode ^
      previewContentBytes.hashCode ^
      assemblyRows.hashCode ^
      assemblyContentBytes.hashCode ^
      unclassifiedRows.hashCode ^
      unclassifiedContentBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryContentReadStats &&
          runtimeType == other.runtimeType &&
          hybridResultRows == other.hybridResultRows &&
          hybridResultContentBytes == other.hybridResultContentBytes &&
          fullHydrateRows == other.fullHydrateRows &&
          fullHydrateContentBytes == other.fullHydrateContentBytes &&
          previewRows == other.previewRows &&
          previewContentBytes == other.previewContentBytes &&
          assemblyRows == other.assemblyRows &&
          assemblyContentBytes == other.assemblyContentBytes &&
          unclassifiedRows == other.unclassifiedRows &&
          unclassifiedContentBytes == other.unclassifiedContentBytes;
}
