// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `enter`, `new`, `record_hybrid_result_content_read`, `record_hydrated_content_read`, `reset`, `snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AtomicTokenizationCounter`, `QueryContentReadGuard`, `QueryContentReadPhase`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`

QueryContentReadStats queryContentReadStats() =>
    RustLib.instance.api.crateApiQueryMetricsQueryContentReadStats();

void resetQueryContentReadStats() =>
    RustLib.instance.api.crateApiQueryMetricsResetQueryContentReadStats();

QueryContentReadStats takeQueryContentReadStats() =>
    RustLib.instance.api.crateApiQueryMetricsTakeQueryContentReadStats();

class QueryContentReadStats {
  final BigInt hybridResultRows;
  final BigInt hybridResultContentBytes;
  final BigInt fullHydrateRows;
  final BigInt fullHydrateContentBytes;
  final BigInt previewRows;
  final BigInt previewContentBytes;
  final BigInt assemblyRows;
  final BigInt assemblyContentBytes;
  final BigInt unclassifiedRows;
  final BigInt unclassifiedContentBytes;
  final BigInt scopedExactScanRows;
  final BigInt scopedExactScanContentBytes;
  final BigInt scopedExactScanTokenizedRows;
  final BigInt scopedExactScanTokenizedContentBytes;
  final BigInt scopedExactScanTokens;
  final BigInt scopedExactScanTokenizationNanos;

  const QueryContentReadStats({
    required this.hybridResultRows,
    required this.hybridResultContentBytes,
    required this.fullHydrateRows,
    required this.fullHydrateContentBytes,
    required this.previewRows,
    required this.previewContentBytes,
    required this.assemblyRows,
    required this.assemblyContentBytes,
    required this.unclassifiedRows,
    required this.unclassifiedContentBytes,
    required this.scopedExactScanRows,
    required this.scopedExactScanContentBytes,
    required this.scopedExactScanTokenizedRows,
    required this.scopedExactScanTokenizedContentBytes,
    required this.scopedExactScanTokens,
    required this.scopedExactScanTokenizationNanos,
  });

  /// Materialized result bytes only — see [`Self::rows_total`].
  Future<BigInt> contentBytesTotal() => RustLib.instance.api
          .crateApiQueryMetricsQueryContentReadStatsContentBytesTotal(
        that: this,
      );

  Future<BigInt> hydrationContentBytesTotal() => RustLib.instance.api
          .crateApiQueryMetricsQueryContentReadStatsHydrationContentBytesTotal(
        that: this,
      );

  Future<BigInt> hydrationRowsTotal() => RustLib.instance.api
          .crateApiQueryMetricsQueryContentReadStatsHydrationRowsTotal(
        that: this,
      );

  /// Materialized result reads only — does NOT include the scoped exact-scan
  /// backend counter, which measures rows scanned during search rather than
  /// rows surfaced as results.
  Future<BigInt> rowsTotal() =>
      RustLib.instance.api.crateApiQueryMetricsQueryContentReadStatsRowsTotal(
        that: this,
      );

  @override
  int get hashCode =>
      hybridResultRows.hashCode ^
      hybridResultContentBytes.hashCode ^
      fullHydrateRows.hashCode ^
      fullHydrateContentBytes.hashCode ^
      previewRows.hashCode ^
      previewContentBytes.hashCode ^
      assemblyRows.hashCode ^
      assemblyContentBytes.hashCode ^
      unclassifiedRows.hashCode ^
      unclassifiedContentBytes.hashCode ^
      scopedExactScanRows.hashCode ^
      scopedExactScanContentBytes.hashCode ^
      scopedExactScanTokenizedRows.hashCode ^
      scopedExactScanTokenizedContentBytes.hashCode ^
      scopedExactScanTokens.hashCode ^
      scopedExactScanTokenizationNanos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryContentReadStats &&
          runtimeType == other.runtimeType &&
          hybridResultRows == other.hybridResultRows &&
          hybridResultContentBytes == other.hybridResultContentBytes &&
          fullHydrateRows == other.fullHydrateRows &&
          fullHydrateContentBytes == other.fullHydrateContentBytes &&
          previewRows == other.previewRows &&
          previewContentBytes == other.previewContentBytes &&
          assemblyRows == other.assemblyRows &&
          assemblyContentBytes == other.assemblyContentBytes &&
          unclassifiedRows == other.unclassifiedRows &&
          unclassifiedContentBytes == other.unclassifiedContentBytes &&
          scopedExactScanRows == other.scopedExactScanRows &&
          scopedExactScanContentBytes == other.scopedExactScanContentBytes &&
          scopedExactScanTokenizedRows == other.scopedExactScanTokenizedRows &&
          scopedExactScanTokenizedContentBytes ==
              other.scopedExactScanTokenizedContentBytes &&
          scopedExactScanTokens == other.scopedExactScanTokens &&
          scopedExactScanTokenizationNanos ==
              other.scopedExactScanTokenizationNanos;
}
