// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `advance_by_chars`, `build_semantic_chunk`, `cached_token_count`, `char_count_in_range`, `enforce_token_budget`, `fits_range`, `fits_token_budget`, `flush_text_section`, `is_article_title`, `is_bullet_line`, `is_markdown_header`, `is_sentence_boundary_char`, `is_table_line`, `largest_fitting_prefix_end`, `largest_token_fitting_prefix_end`, `line_content_end`, `markdown_line_ranges`, `materialize_semantic_chunks`, `new`, `next_non_whitespace`, `overlap_boundary_starts`, `overlap_start`, `parse_code_block_language`, `parse_markdown_header`, `plan_plain_text_ranges_char_budget`, `plan_plain_text_ranges`, `plan_plain_text_subranges`, `split_by_headers`, `split_by_line_ranges`, `split_hard_range`, `split_line_ranges`, `split_paragraph_ranges`, `split_semantic_range`, `split_token_budget_range`, `subslice_range`, `token_count_cache_key`, `trim_range`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChunkingStrategy`, `MarkdownLine`, `PlainTextPlanner`, `Section`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Classify chunk by rule-based pattern matching.
ChunkType classifyChunk({required String text}) =>
    RustLib.instance.api.crateApiSemanticChunkerClassifyChunk(text: text);

/// Split text into semantic chunks using paragraph-first strategy.
List<SemanticChunk> semanticChunk({
  required String text,
  required int maxChars,
}) => RustLib.instance.api.crateApiSemanticChunkerSemanticChunk(
  text: text,
  maxChars: maxChars,
);

/// Split text with overlap (API compatibility wrapper).
List<SemanticChunk> semanticChunkWithOverlap({
  required String text,
  required int maxChars,
  required int overlapChars,
}) => RustLib.instance.api.crateApiSemanticChunkerSemanticChunkWithOverlap(
  text: text,
  maxChars: maxChars,
  overlapChars: overlapChars,
);

/// Markdown chunk with structure preservation and metadata inheritance.
///
/// - Splits by Markdown headers (#, ##, ###)
/// - Preserves code blocks (```) as single units
/// - Preserves tables (|---|) as single units
/// - Inherits header path as metadata
List<StructuredChunk> markdownChunk({
  required String text,
  required int maxChars,
}) => RustLib.instance.api.crateApiSemanticChunkerMarkdownChunk(
  text: text,
  maxChars: maxChars,
);

/// Chunk type classification.
enum ChunkType {
  definition,
  example,
  list,
  procedure,
  comparison,
  general;

  Future<void> asStr() =>
      RustLib.instance.api.crateApiSemanticChunkerChunkTypeAsStr(that: this);

  static Future<ChunkType> fromStr({required String s}) =>
      RustLib.instance.api.crateApiSemanticChunkerChunkTypeFromStr(s: s);
}

/// Semantic chunk result.
class SemanticChunk {
  final int index;
  final String content;
  final int startPos;
  final int endPos;
  final String chunkType;

  const SemanticChunk({
    required this.index,
    required this.content,
    required this.startPos,
    required this.endPos,
    required this.chunkType,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      content.hashCode ^
      startPos.hashCode ^
      endPos.hashCode ^
      chunkType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SemanticChunk &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          content == other.content &&
          startPos == other.startPos &&
          endPos == other.endPos &&
          chunkType == other.chunkType;
}

/// Structured chunk with header path for context inheritance.
class StructuredChunk {
  final int index;
  final String content;
  final String headerPath;
  final String chunkType;
  final int startPos;
  final int endPos;
  final String? batchId;
  final int? batchIndex;
  final int? batchTotal;

  const StructuredChunk({
    required this.index,
    required this.content,
    required this.headerPath,
    required this.chunkType,
    required this.startPos,
    required this.endPos,
    this.batchId,
    this.batchIndex,
    this.batchTotal,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      content.hashCode ^
      headerPath.hashCode ^
      chunkType.hashCode ^
      startPos.hashCode ^
      endPos.hashCode ^
      batchId.hashCode ^
      batchIndex.hashCode ^
      batchTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredChunk &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          content == other.content &&
          headerPath == other.headerPath &&
          chunkType == other.chunkType &&
          startPos == other.startPos &&
          endPos == other.endPos &&
          batchId == other.batchId &&
          batchIndex == other.batchIndex &&
          batchTotal == other.batchTotal;
}
