// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Simple greeting function for FRB demo.
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Runs a micro-benchmark for VABQ similarity computation on the device.
/// Returns the average nanoseconds per computation.
BigInt benchmarkVabqDevice({required BigInt dim, required int iterations}) =>
    RustLib.instance.api.crateApiSimpleBenchmarkVabqDevice(
      dim: dim,
      iterations: iterations,
    );
