// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sets the explicit VABQ profile chosen by the host after probing its model.
/// Passing `null` selects Q8_0 fallback. A selected profile must match the
/// supplied embedding dimension or initialization fails closed.
Future<void> configureVabqProfile({
  String? profile,
  required int embeddingDimension,
}) => RustLib.instance.api.crateApiVabqConfigConfigureVabqProfile(
  profile: profile,
  embeddingDimension: embeddingDimension,
);
